version: "3.7"
services:
  laravel-web:
    # env_file:
    #    - ./www/laravel-web/.env
    build: 
      context: .
      args:
        uid: ${UID}
    image: laravel7/sms-web-app:${TAG}
    depends_on:
      - mysql-db
      - redis-cache
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=sms-mysql-app
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DB=${DB_DATABASE}
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./www/:/var/www/html/
    ports:
      # - "30001:80"
      - "${HOST_PORT}:80"
    container_name: sms-web-app

  mysql-db:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD} 
      - MYSQL_DATABASE=${DB_DATABASE}
    container_name: sms-mysql-app

  redis-cache:
    image: redis:alpine
    ports:
      # - "6379"
      - "6363:6379"
    networks:
      - frontend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - mysql-db
    networks:
      - backend
    ports:
      - "30002:80"
    environment:
      - PMA_HOST=sms-mysql-app
      - PMA_PORT=${DB_PORT}
    volumes:
      - /sessions
    container_name: sms-phpmyadmin-app
networks:
  frontend:
  backend:
